#!/usr/bin/env node

/**
 * Create a new Superdesigner project.
 * Usage: superdesigner init "Project Name"
 */

import { existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { slugify } from '../lib/slugify.mjs';
import { copyTemplate, getProjectPath, getContextPath, getInsightsPath, writeFile } from '../lib/files.mjs';

// Get project name from command line args
const args = process.argv.slice(2);

if (args.length === 0) {
  console.error('❌ Error: Please provide a project name.');
  console.error('');
  console.error('Usage: superdesigner init "Project Name"');
  console.error('Example: superdesigner init "Botim Quest"');
  process.exit(1);
}

const projectName = args.join(' ');
const slug = slugify(projectName);

if (!slug) {
  console.error('❌ Error: Invalid project name. Please use letters and numbers.');
  process.exit(1);
}

const projectPath = getProjectPath(slug);

// Check if project already exists
if (existsSync(projectPath)) {
  console.error(`❌ Error: Project "${slug}" already exists.`);
  console.error(`   Path: ${projectPath}`);
  process.exit(1);
}

// Create project directory structure
mkdirSync(projectPath, { recursive: true });

const contextPath = getContextPath(slug);
const insightsPath = getInsightsPath(slug);

mkdirSync(contextPath, { recursive: true });
mkdirSync(insightsPath, { recursive: true });

// Meta values for template headers
const meta = {
  projectName: projectName,
  createdDate: new Date().toISOString()
};

// Templates to copy to context/ folder
const templates = [
  ['prd.template.md', 'prd.md'],
  ['research.template.md', 'research.md'],
  ['figma.template.md', 'figma.md'],
  ['analytics.template.md', 'analytics.md']
];

// Copy each template to context/
for (const [templateName, outputName] of templates) {
  const destPath = join(contextPath, outputName);
  copyTemplate(templateName, destPath, meta);
}

// Create README files
const projectReadme = `# ${projectName}

## Quick Start

1. Edit files in \`context/\` with your requirements
2. Run: \`superdesigner review ${slug}\`
3. Review generated insights in \`insights/\`

## Folders

- \`context/\` - Your input files (PRD, research, Figma links)
- \`insights/\` - Generated design review and comments
`;

const contextReadme = `# Context

✍️ Edit these files. This is the context Superdesigner uses to reason.

- **prd.md** - Product requirements document
- **research.md** - User research and findings
- **figma.md** - Figma file links
- **analytics.md** - Analytics requirements
`;

const insightsReadme = `# Insights

🤖 Generated by Superdesigner. Do not edit manually.

These files are regenerated each time you run \`superdesigner review\`.
`;

writeFile(join(projectPath, 'README.md'), projectReadme);
writeFile(join(contextPath, 'README.md'), contextReadme);
writeFile(join(insightsPath, 'README.md'), insightsReadme);

// Success output
console.log('');
console.log(`✅ Created project: ${projectName}`);
console.log(`   Folder: projects/${slug}/`);
console.log('');
console.log('📁 Files created:');
console.log('   context/');
console.log('     - prd.md         (Product requirements)');
console.log('     - research.md    (Research notes)');
console.log('     - figma.md       (Figma link)');
console.log('     - analytics.md   (Analytics requirements)');
console.log('   insights/          (Generated outputs go here)');
console.log('');
console.log('📝 Next steps:');
console.log('   1. Edit context/prd.md with your requirements');
console.log('   2. Add your Figma link in context/figma.md');
console.log(`   3. Run: superdesigner review ${slug} --agent`);
console.log('');
