#!/usr/bin/env node

/**
 * Generate design review prompts for Cursor Agent.
 * Usage: npm run review -- <project-slug>
 *        npm run review -- all
 */

import { join } from 'path';
import { mkdirSync, existsSync } from 'fs';
import { readFile, writeFile, listProjectDirs, getProjectPath, projectExists } from '../lib/files.mjs';
import { extractHeadings, extractBullets, extractSection, extractNodeId } from '../lib/generator.mjs';

/**
 * Design Review template - exact structure for Cursor Agent.
 */
const DESIGN_REVIEW_TEMPLATE = `# Design Review: <Project Name>

*Generated on <DATE>*

---

## 1. Intended Flow (from PRD)

<List the happy path steps as numbered list>

## 2. Expected Screens (inferred)

<List screens as checkboxes>

## 3. States Checklist

Every screen should account for these states:

- [ ] **Happy path** — The ideal user journey
- [ ] **Empty** — No data, first-time user, or cleared state
- [ ] **Loading** — Waiting for data or action completion
- [ ] **Error** — Something went wrong (network, validation, permissions)
- [ ] **Recovery** — How the user gets back on track

## 4. Gaps & Risks

### Edge cases identified:
<List edge cases with ⚠️ prefix>

### Common gaps to check:
- [ ] Offline behavior
- [ ] Permission denied states
- [ ] Session timeout handling
- [ ] Rate limiting / throttling
- [ ] Accessibility considerations

## 5. Suggestions

<3-5 actionable suggestions based on the analysis>

## 6. Figma Make Prompt

\`\`\`
Create a prototype skeleton for "<Project Name>".

## Context
<Overview from PRD>

## Problem
<Problem statement from PRD>

## Goals
<Goals from PRD as bullets>

## User Flow
<Happy path steps as numbered list>

## Required Frames
<List of screens>

## States (for each screen)
- Default (happy path)
- Empty state
- Loading state
- Error state

Focus on flow and structure, not visual polish.
\`\`\`

---

*Review generated by Superdesigner*
`;

/**
 * Design Comments template - exact structure for Cursor Agent.
 */
const DESIGN_COMMENTS_TEMPLATE = `# Design Comments Preview
Project: <Project Name>
Generated: <DATE>

---

## Comment 1
Target:
  page: <Screen name>
  frame: (optional)
  nodeId: <Node ID if available>

Type:
  <Missing State | Flow Mismatch | Edge Case | Validation | Clarifying Question>

Message:
<The actual comment text - be specific and actionable>

Why:
<Reference to PRD section or UX principle>

---

<Repeat for 3-7 comments total>

*Total: X comments*
*Run \`npm run comment -- <slug>\` to post to Figma.*
`;

/**
 * Generate context file content from artifacts.
 */
function generateContext(artifacts, projectName, slug) {
  const { prd, research, figma, analytics } = artifacts;
  
  const happyPath = extractBullets(prd, 'happy path');
  const edgeCases = extractBullets(prd, 'edge case');
  const goals = extractBullets(prd, 'goals');
  const overview = extractSection(prd, 'overview');
  const problem = extractSection(prd, 'problem');
  const headings = extractHeadings(prd);
  const nodeId = extractNodeId(figma);
  
  const date = new Date().toISOString();
  
  let context = `# Superdesigner Review Context
Project: ${projectName}
Slug: ${slug}
Generated: ${date}

---

## Extracted from PRD

### Overview
${overview || '*Not found in PRD*'}

### Problem Statement
${problem || '*Not found in PRD*'}

### Goals
${goals.length > 0 ? goals.map(g => `- ${g}`).join('\n') : '*Not found in PRD*'}

### Happy Path
${happyPath.length > 0 ? happyPath.map((s, i) => `${i + 1}. ${s}`).join('\n') : '*Not found in PRD - add a "Happy path" section*'}

### Edge Cases
${edgeCases.length > 0 ? edgeCases.map(e => `- ${e}`).join('\n') : '*Not found in PRD - add an "Edge cases" section*'}

### PRD Headings (for screen inference)
${headings.map(h => `- ${h}`).join('\n')}

---

## Extracted from Figma

### Node ID (for comment pinning)
${nodeId || '*No node-id found in figma.md URL*'}

---

## Extracted from Research

${research ? research.slice(0, 2000) : '*No research.md content*'}

---

## Extracted from Analytics

${analytics ? analytics.slice(0, 1000) : '*No analytics.md content*'}
`;

  return context;
}

/**
 * Generate prompt file content.
 */
function generatePrompt(projectName, slug) {
  return `# Superdesigner Review Prompt

Read \`_review_context.md\` in this folder and generate the design review documents.

## Rules (STRICT)

1. **Do NOT invent requirements** — only use what's in the context file
2. **Be specific** — reference actual steps, screens, and edge cases from the PRD
3. **Be actionable** — every suggestion should be something the designer can do
4. **Use the templates exactly** — follow the structure provided below

## Output (EXACTLY two files)

Create these files in the parent project folder (\`projects/${slug}/\`):

### 1. \`design-review.md\`

Use this EXACT template:

\`\`\`markdown
${DESIGN_REVIEW_TEMPLATE}
\`\`\`

### 2. \`design-comments.preview.md\`

Use this EXACT template:

\`\`\`markdown
${DESIGN_COMMENTS_TEMPLATE}
\`\`\`

## Instructions

1. Read the context file to understand the project
2. Generate \`design-review.md\` with:
   - Intended flow from the happy path steps
   - Expected screens inferred from PRD headings
   - Edge cases listed under Gaps & Risks
   - Figma Make prompt with full project context
3. Generate \`design-comments.preview.md\` with:
   - 3-7 high-signal comments
   - Focus on missing states, edge cases, and clarifying questions
   - Include nodeId if available from context
4. Replace all \`<placeholders>\` with actual content
5. Replace \`<DATE>\` with: ${new Date().toISOString().split('T')[0]}
6. Replace \`<Project Name>\` with: ${projectName}

## After generation

Run \`npm run comment -- ${slug} --dry-run\` to preview Figma comments.
`;
}

/**
 * Run review for a single project.
 */
function reviewProject(slug) {
  if (!projectExists(slug)) {
    console.error(`❌ Error: Project "${slug}" not found.`);
    console.error('');
    console.error('Available projects:');
    listProjectDirs().forEach(p => console.error(`   - ${p}`));
    return false;
  }

  const projectPath = getProjectPath(slug);
  const promptsPath = join(projectPath, 'prompts');
  
  // Ensure prompts folder exists
  if (!existsSync(promptsPath)) {
    mkdirSync(promptsPath, { recursive: true });
  }

  // Read all artifacts
  const artifacts = {
    prd: readFile(join(projectPath, 'prd.md')),
    research: readFile(join(projectPath, 'research.md')),
    figma: readFile(join(projectPath, 'figma.md')),
    analytics: readFile(join(projectPath, 'analytics.md'))
  };

  // Extract project name from PRD header or use slug
  const projectNameMatch = artifacts.prd.match(/^Project:\s*(.+)$/m);
  const projectName = projectNameMatch ? projectNameMatch[1].trim() : slug;

  // Generate context and prompt files
  const contextContent = generateContext(artifacts, projectName, slug);
  const promptContent = generatePrompt(projectName, slug);

  // Write to prompts folder
  const contextPath = join(promptsPath, '_review_context.md');
  const promptPath = join(promptsPath, '_review_prompt.md');
  
  writeFile(contextPath, contextContent);
  writeFile(promptPath, promptContent);

  console.log(`✅ ${slug}`);
  console.log(`   → prompts/_review_context.md`);
  console.log(`   → prompts/_review_prompt.md`);
  
  return true;
}

// Parse command line args
const args = process.argv.slice(2);

if (args.length === 0) {
  console.error('❌ Error: Please provide a project slug or "all".');
  console.error('');
  console.error('Usage: npm run review -- <project-slug>');
  console.error('       npm run review -- all');
  console.error('');
  console.error('Available projects:');
  const projects = listProjectDirs();
  if (projects.length === 0) {
    console.error('   (none - create one with: npm run new -- "Project Name")');
  } else {
    projects.forEach(p => console.error(`   - ${p}`));
  }
  process.exit(1);
}

const target = args[0];

console.log('');
console.log('🔍 Superdesigner Review');
console.log('');

if (target === 'all') {
  const projects = listProjectDirs();
  
  if (projects.length === 0) {
    console.error('❌ No projects found.');
    console.error('   Create one with: npm run new -- "Project Name"');
    process.exit(1);
  }
  
  console.log(`Preparing ${projects.length} project(s)...`);
  console.log('');
  
  let successCount = 0;
  for (const slug of projects) {
    if (reviewProject(slug)) {
      successCount++;
    }
  }
  
  console.log('');
  console.log(`✅ Completed: ${successCount}/${projects.length} projects`);
} else {
  const success = reviewProject(target);
  if (!success) {
    process.exit(1);
  }
}

console.log('');
console.log('📝 Next steps:');
console.log('   1. Open prompts/_review_prompt.md in Cursor');
console.log('   2. Run with Cursor Agent (Cmd+I / Ctrl+I → Agent mode)');
console.log('   3. It will create design-review.md and design-comments.preview.md');
console.log('');
